---
name: release-template
on:
  workflow_call:
    inputs:
      param:
        type: string
      repositories:
        type: string
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          false

  update-dependent-repositories:
    name: Update ${{ matrix.repository }}
    strategy:
      matrix:
        matrixval: ${{fromJson(inputs.repositories)}}
    needs: create-release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && inputs.repositories }}
    steps:
      - name: step 3
        id: get-tag-step
        run: |
          echo head_branch=${{github.event.workflow_run.head_branch}}
          echo '::set-output name=tag::something'
          echo 'matrixval=1'
      - name: step 4
        run: |
          echo tag=${{ steps.get-tag-step.outputs.tag }}
          echo param=${{ inputs.param }}
