---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  step0:
    uses: ./.github/workflows/release-template.yaml
    with:
      param: ppp
      repositories: >-
        [
          "cmd-forwarder-sriov",
          "cmd-nsc",
          "cmd-nsc-init",
          "cmd-nse-icmp-responder",
          "cmd-forwarder-vpp",
          "cmd-nse-vlan-vpp",
          "sdk-ovs",
        ]
